resources:
- name: leaf
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/leaf.git

- name: collenchyma-nn
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/collenchyma-nn.git

- name: collenchyma-blas
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/collenchyma-blas.git

- name: collenchyma
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/collenchyma.git

- name: cuticula
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/cuticula.git

- name: rust-cudnn
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/rust-cudnn.git

- name: rust-cublas
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/rust-cublas.git

- name: continuous-integration
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/continuous-integration.git

- name: container
  type: docker-image
  source:
    repository: quay.io/ratpoison/machine-learning-container
    username: {{quay-username}}
    password: {{quay-password}}


jobs:
  - name: build-container
    public: true
    plan:
      - get: continuous-integration
        trigger: true
      - put: container
        params:
          cache: true
          tag_as_latest: true
          build: continuous-integration/container

  - name: test-collenchyma
    public: true
    plan:
    - aggregate:
      - get: rust-cudnn
        trigger: true
      - get: rust-cublas
        trigger: true
      - get: collenchyma
        trigger: true
      - get: container
        trigger: true
        passed: [build-container]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cublas
        - name: rust-cudnn
        - name: collenchyma
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "collenchyma"


  - name: test-collenchyma-blas
    public: true
    plan:
    - aggregate:
      - get: rust-cublas
        trigger: true
      - get: collenchyma
        trigger: true
      - get: collenchyma-blas
        trigger: true
      - get: container
        trigger: true
        passed: [build-container, test-collenchyma]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cublas
        - name: collenchyma
        - name: collenchyma-blas
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "collenchyma-blas"

  - name: test-collenchyma-nn
    public: true
    plan:
    - aggregate:
      - get: rust-cudnn
        trigger: true
      - get: rust-cublas
        trigger: true
      - get: collenchyma
        trigger: true
      - get: collenchyma-blas
        trigger: true
      - get: collenchyma-nn
        trigger: true
      - get: container
        trigger: true
        passed: [build-container, test-collenchyma]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-cublas
        - name: collenchyma
        - name: collenchyma-blas
        - name: collenchyma-nn
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "collenchyma-nn"

  - name: test-leaf
    public: true
    plan:
    - aggregate:
      - get: rust-cudnn
        trigger: true
      - get: rust-cublas
        trigger: true
      - get: collenchyma
        trigger: true
      - get: collenchyma-blas
        trigger: true
      - get: collenchyma-nn
        trigger: true
      - get: leaf
        trigger: true
      - get: container
        trigger: true
        passed: [build-container, test-collenchyma, test-collenchyma-nn, test-collenchyma-blas]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-cublas
        - name: collenchyma
        - name: collenchyma-blas
        - name: collenchyma-nn
        - name: leaf
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "collenchyma-nn"

  - name: test-cuticula
    public: true
    plan:
    - aggregate:
      - get: rust-cudnn
        trigger: true
      - get: rust-cublas
        trigger: true
      - get: collenchyma
        trigger: true
      - get: collenchyma-blas
        trigger: true
      - get: collenchyma-nn
        trigger: true
      - get: cuticula
        trigger: true
      - get: container
        trigger: true
        passed: [build-container, test-collenchyma, test-collenchyma-nn, test-collenchyma-blas]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-cublas
        - name: collenchyma
        - name: cuticula
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "cuticula"
