resources:
- name: leaf-examples
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/leaf-examples.git

- name: leaf
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/leaf.git

- name: coaster-nn
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/coaster-nn.git

- name: coaster-blas
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/coaster-blas.git

- name: coaster
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/coaster.git

- name: greenglas
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/greenglas.git

- name: rust-cudnn
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/rust-cudnn.git

- name: rust-cublas
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/rust-cublas.git

- name: rust-blas
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/rust-blas.git

- name: container
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container
    username: {{quay-username}}
    password: {{quay-password}}


jobs:
  - name: test-coaster
    public: true
    plan:
    - aggregate:
      - get: coaster
        trigger: true
      - get: container
        trigger: true
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: coaster
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "coaster"


  - name: test-coaster-blas
    public: true
    plan:
    - aggregate:
      - get: rust-cublas
        trigger: true
      - get: coaster
        trigger: true
      - get: coaster-blas
        trigger: true
      - get: rust-blas
        trigger: true
      - get: container
        trigger: true
        passed: [test-coaster]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "coaster-blas"

  - name: test-coaster-nn
    public: true
    plan:
    - aggregate:
      - get: rust-cudnn
        trigger: true
      - get: rust-blas
        trigger: true
      - get: rust-cublas
        trigger: true
      - get: coaster
        trigger: true
      - get: coaster-blas
        trigger: true
      - get: coaster-nn
        trigger: true
      - get: container
        trigger: true
        passed: [test-coaster]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        - name: coaster-nn
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "coaster-nn"

  - name: test-greenglas
    public: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster
        trigger: true
      - get: coaster-blas
        trigger: true
      - get: coaster-nn
        trigger: true
      - get: greenglas
        trigger: true
      - get: container
        trigger: true
        passed: [test-coaster, test-coaster-nn, test-coaster-blas]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: greenglas
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "greenglas"


  - name: test-leaf
    public: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster
        trigger: true
      - get: coaster-blas
        trigger: true
      - get: coaster-nn
        trigger: true
      - get: leaf
        trigger: true
      - get: container
        trigger: true
        passed: [test-coaster, test-coaster-nn, test-coaster-blas]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        - name: coaster-nn
        - name: leaf
        run:
          path: cargo
          args: ["test", "--no-default-features","--features=native"]
          dir: "coaster-nn"

  - name: test-leaf-examples
    public: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster-blas
      - get: coaster-nn
      - get: coaster
        trigger: true
      - get: leaf
        trigger: true
      - get: leaf-examples
        trigger: true
      - get: container
        trigger: true
        passed: [test-coaster, test-leaf, test-greenglas]
    - task: compile
      image: container
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        - name: coaster-nn
        - name: leaf
        - name: leaf-examples
        run:
          path: cargo
          args: ["b", "--no-default-features","--features=native"]
          dir: "leaf-examples"
