resources:
- name: git-ci
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/continuous-integration.git


- name: container-fedora-cuda
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-cuda
    username: ((quay-username))
    password: ((quay-password))

- name: container-fedora-default
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-default
    username: ((quay-username))
    password: ((quay-password))

- name: container-fedora-native
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-native
    username: ((quay-username))
    password: ((quay-password))

- name: container-fedora-opencl
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-opencl
    username: ((quay-username))
    password: ((quay-password))



- name: container-ubuntu-native
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-native
    username: ((quay-username))
    password: ((quay-password))

- name: container-ubuntu-opencl
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-opencl
    username: ((quay-username))
    password: ((quay-password))





- name: container-doc
  type: docker-image
  source:
    repository: quay.io/spearow/doc-gen-container
    username: ((quay-username))
    password: ((quay-password))

- name: container-fedora
  type: docker-image
  source:
    repository: fedora



jobs:
  - name: build-misc
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container-fedora
      resource: container-fedora
    - task: gen-doc
      image: container-fedora
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/misc/* ./copycat/
            cp -rfv ci/container/*.sh ./copycat/
    - put: container-doc
      params:
        build: copycat
        tag_as_latest: true



  - name: build-fedora-cuda
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container-doc
      resource: container-doc
    - task: gen-doc
      image: container-doc
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/cuda/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/
    - put: container-fedora-cuda
      params:
        build: copycat
        tag_as_latest: true

  - name: build-fedora-default
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container-doc
      resource: container-doc
    - task: gen-doc
      image: container-doc
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/default/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/
    - put: container-fedora-default
      params:
        build: copycat
        tag_as_latest: true

  - name: build-fedora-native
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container-doc
      resource: container-doc
    - task: gen-doc
      image: container-doc
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/native/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/
    - put: container-fedora-native
      params:
        build: copycat
        tag_as_latest: true

  - name: build-fedora-opencl
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container-doc
      resource: container-doc
    - task: gen-doc
      image: container-doc
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/opencl/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/
    - put: container-fedora-opencl
      params:
        build: copycat
        tag_as_latest: true



  - name: build-ubuntu-native
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container-doc
      resource: container-doc
    - task: gen-doc
      image: container-doc
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/ubuntu ./copycat/
            cp -rfv ci/container/ubuntu/native/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/
    - put: container-ubuntu-native
      params:
        build: copycat
        tag_as_latest: true

  - name: build-ubuntu-opencl
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container-doc
      resource: container-doc
    - task: gen-doc
      image: container-doc
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/ubuntu ./copycat/
            cp -rfv ci/container/ubuntu/opencl/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/
    - put: container-ubuntu-opencl
      params:
        build: copycat
        tag_as_latest: true



