resources:
- name: git-ci
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/continuous-integration.git



- name: container-fedora-cuda
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-cuda
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2

- name: container-fedora-default
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-default
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2

- name: container-fedora-native
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-native
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2

- name: container-fedora-opencl
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-opencl
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2



- name: container-ubuntu-native
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-native
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2

- name: container-ubuntu-opencl
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-opencl
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2



- name: container-misc
  type: docker-image
  source:
    repository: quay.io/spearow/doc-gen-container
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2

- name: container-fedora-base
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-base
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2

- name: container-ubuntu-base
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-base
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
    max_concurrent_downloads: 2
    max_concurrent_uploads: 2


jobs:
  - name: build-misc
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container
      resource: container-misc

    - get: container-fedora-base
      params: { save: true }

    - task: gen-misc
      image: container
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/misc/Dockerfile ./copycat/
            cp -rfv ci/container/misc ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-misc
      params:
        load_base: container-fedora-base
        build: copycat
        tag_as_latest: true



  - name: create-oci-fedora-base
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-fedora-base

    - task: composition
      image: container-fedora-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-fedora-base
      params:
        build: copycat
        tag_as_latest: true


  - name: create-oci-fedora-cuda
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-fedora-base
      passed: [create-oci-fedora-base]
      params: { save: true }

    - task: composition
      image: container-fedora-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/cuda/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-fedora-cuda
      params:
        load_base: container-fedora-base
        build: copycat
        tag_as_latest: true


  - name: create-oci-fedora-default
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-fedora-base
      passed: [create-oci-fedora-base]
      params: { save: true }

    - task: composition
      image: container-fedora-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/default/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-fedora-default
      params:
        load_base: container-fedora-base
        build: copycat
        tag_as_latest: true


  - name: create-oci-fedora-native
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-fedora-base
      passed: [create-oci-fedora-base]
      params: { save: true }

    - task: composition
      image: container-fedora-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/native/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-fedora-native
      params:
        load_base: container-fedora-base
        build: copycat
        tag_as_latest: true


  - name: create-oci-fedora-opencl
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-fedora-base
      passed: [create-oci-fedora-base]
      params: { save: true }

    - task: composition
      image: container-fedora-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/opencl/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-fedora-opencl
      params:
        load_base: container-fedora-base
        build: copycat
        tag_as_latest: true



  - name: create-oci-ubuntu-base
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-fedora-base

    - task: composition
      image: container-fedora-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/ubuntu ./copycat/
            cp -rfv ci/container/ubuntu/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-ubuntu-base
      params:
        build: copycat
        tag_as_latest: true


  - name: create-oci-ubuntu-native
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-ubuntu-base
      passed: [create-oci-ubuntu-base]
      params: { save: true }

    - task: composition
      image: container-ubuntu-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/ubuntu ./copycat/
            cp -rfv ci/container/ubuntu/native/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-ubuntu-native
      params:
        load_base: container-ubuntu-base
        build: copycat
        tag_as_latest: true


  - name: create-oci-ubuntu-opencl
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-ubuntu-base
      passed: [create-oci-ubuntu-base]
      params: { save: true }

    - task: composition
      image: container-ubuntu-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/ubuntu ./copycat/
            cp -rfv ci/container/ubuntu/opencl/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-ubuntu-opencl
      params:
        load_base: container-ubuntu-base
        build: copycat
        tag_as_latest: true


