resources:
- name: git-continuous-integration
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/continuous-integration.git

- name: container-fedora-cuda
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-cuda
    username: ((quay-username))
    password: ((quay-password))

- name: container-fedora-default
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-default
    username: ((quay-username))
    password: ((quay-password))

- name: container-fedora-native
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-native
    username: ((quay-username))
    password: ((quay-password))

- name: container-fedora-opencl
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-opencl
    username: ((quay-username))
    password: ((quay-password))



- name: container-pureos-cuda
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-pureos-cuda
    username: ((quay-username))
    password: ((quay-password))

- name: container-pureos-default
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-pureos-default
    username: ((quay-username))
    password: ((quay-password))

- name: container-pureos-native
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-pureos-native
    username: ((quay-username))
    password: ((quay-password))

- name: container-pureos-opencl
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-pureos-opencl
    username: ((quay-username))
    password: ((quay-password))



- name: container-ubuntu-cuda
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-cuda
    username: ((quay-username))
    password: ((quay-password))

- name: container-ubuntu-default
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-default
    username: ((quay-username))
    password: ((quay-password))

- name: container-ubuntu-native
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-native
    username: ((quay-username))
    password: ((quay-password))

- name: container-ubuntu-opencl
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container-ubuntu-opencl
    username: ((quay-username))
    password: ((quay-password))



- name: container
  type: docker-image
  source:
    repository: quay.io/spearow/machine-learning-container
    username: ((quay-username))
    password: ((quay-password))



jobs:


  - name: build-fedora-cuda
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: fedora/cuda/
        tag_as_latest: true

  - name: build-fedora-default
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: fedora/default/
        tag_as_latest: true

  - name: build-fedora-native
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: fedora/native/
        tag_as_latest: true

  - name: build-fedora-opencl
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: fedora/opencl/
        tag_as_latest: true



  - name: build-pureos-cuda
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: pureos/cuda/
        tag_as_latest: true

  - name: build-pureos-default
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: pureos/default/
        tag_as_latest: true

  - name: build-pureos-native
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: pureos/native/
        tag_as_latest: true

  - name: build-pureos-opencl
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: pureos/opencl/
        tag_as_latest: true



  - name: build-ubuntu-cuda
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: ubuntu/cuda/
        tag_as_latest: true

  - name: build-ubuntu-default
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: ubuntu/default/
        tag_as_latest: true

  - name: build-ubuntu-native
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: ubuntu/native/
        tag_as_latest: true

  - name: build-ubuntu-opencl
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: ubuntu/opencl/
        tag_as_latest: true

