FROM fedora:latest
LABEL maintainer="Bernhard Schuster <bernhard@juice.fff.rs>"
#RUN dnf update -y

COPY misc/pkg.sh /tmp/pkg.sh

RUN chmod +x /tmp/pkg.sh && \
	/tmp/pkg.sh && \
	dnf clean all

RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y

ENV PATH=/root/.cargo/bin:$PATH
ENV CMAKE_MAKE_PROGRAM=make

COPY misc/tooling.sh /tmp/tooling.sh
RUN source /tmp/tooling.sh

RUN chmod +x /usr/local/bin/*
