FROM quay.io/fff/machine-learning-container-fedora-base:latest
LABEL maintainer="Bernhard Schuster <bernhard@juice.fff.rs>"

COPY fedora/default/pkg.sh /tmp/pkg.sh

RUN chmod +x /tmp/*.sh && \
	/tmp/pkg.sh && \
	dnf clean all

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=11.0"

COPY escalate.sh /usr/local/bin/escalate
COPY fedora/default/prepare.sh /usr/local/bin/prepare
COPY cargo-override-injection.sh /usr/local/bin/cargo-override-injection

RUN chmod +x /usr/local/bin/*
