                # two levels up is the cache
                export CARGO_HOME=$(pwd)/../../cargo_home
                echo "Sweet (cached) home is \"$CARGO_HOME\""
                mkdir -p $CARGO_HOME
