resources:
- name: git-ci
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/continuous-integration.git

{% include "container-resources.yml" %}
{% include "container-resources-preload.yml" %}

jobs:
  - name: build-misc
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container
      resource: container-fedora

    - get: fedora-preload
      params: { save: true }

    - task: gen-misc
      image: container
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/misc/Dockerfile ./copycat/
            cp -rfv ci/container/misc ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-misc
      params:
        load_base: fedora-preload
        build: copycat
        tag_as_latest: true


{% for testenv in testenvs %}
{% for backend in testenv.backends %}
  - name: build-{{ testenv.name }}-{{ backend }}
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container
      resource: container-misc

{% if testenv.name.as_str() == "fedora" %}
    - get: fedora-preload
      params: { save: true }

{% else if testenv.name.as_str() == "ubuntu" %}
    - get: ubuntu-preload
      params: { save: true }

{% endif %}

    - task: composition
      image: container
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/{{ testenv.name }} ./copycat/
            cp -rfv ci/container/{{ testenv.name }}/{{ backend }}/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-{{ testenv.name }}-{{ backend }}
      params:
{% if testenv.name.as_str() == "fedora" %}
        load_base: fedora-preload
{% else if testenv.name.as_str() == "ubuntu" %}
        load_base: ubuntu-preload
{% endif %}
        build: copycat
        tag_as_latest: true

{% endfor %}
{% endfor %}
