resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource


resources:

{% include "doc-resources.yml" %}

{% include "pr-resources.yml" %}

{% include "master-resources.yml" %}

{% include "container-resources.yml" %}

groups:
- name: stack
  jobs:
  - test-juice

- name: documentation
  jobs:
  - doc-juice

- name: pull-request
  jobs:
  - pr-test-juice

jobs:

{% include "doc.yml" %}

{% include "pr.yml" %}

{% include "master.yml" %}
