resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: juice-examples
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/juice-examples.git

- name: juice
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/juice.git

- name: coaster-nn
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/coaster-nn.git

- name: coaster-blas
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/coaster-blas.git

- name: coaster
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/coaster.git

- name: greenglas
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/greenglas.git

- name: rust-cudnn
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/rust-cudnn.git

- name: rust-cublas
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/rust-cublas.git

- name: rust-blas
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/rust-blas.git


{%- include "doc-resources.yml" %}


{%- include "pr-resources.yml" %}


{%- include "container-resources.yml" %}


groups:
- name: stack
  jobs:
  - test-coaster
  - test-coaster-nn
  - test-coaster-blas
  - test-juice
  - test-juice-examples
  - test-greenglas
  - test-rust-blas
  - test-rust-cudnn
  - test-rust-cublas
- name: documentation
  jobs:
  - doc-coaster
  - doc-coaster-nn
  - doc-coaster-blas
  - doc-greenglas
  - doc-juice
- name: pull-request
  jobs:
  - pr-test-coaster
  - pr-test-coaster-nn
  - pr-test-coaster-blas
  - pr-test-juice
  - pr-test-juice-examples
  - pr-test-greenglas
  - pr-test-rust-blas
  - pr-test-rust-cudnn
  - pr-test-rust-cublas

jobs:
  - name: doc-coaster
    build_logs_to_retain: 2
    public: true
    serial: true
    plan:
    - aggregate:
      - get: doc-coaster
      - get: coaster
        trigger: true
        passed: [test-coaster]
      - get: container-misc
        trigger: true
    - task: gen-doc
      image: container-misc
      config:
        platform: linux
        inputs:
        - name: coaster
        - name: doc-coaster
        outputs:
        - name: doc-coaster-updated
        run:
          path: sh
          args:
          - -exc
          - |
            cd coaster
            cargo doc --no-deps
            cd -
            git clone doc-coaster doc-coaster-updated
            rm -rf doc-coaster-updated/*
            cp -rf coaster/target/doc/* doc-coaster-updated/
            cd doc-coaster-updated
            echo "<meta http-equiv=refresh content=0;url=coaster/index.html>" > index.html
            git config --global user.email "sirmergealot@spearow.io"
            git config --global user.name "Sir Mergealot"
            git add -A && git commit -m"doc/automatic: update" || true
    - put: doc-coaster
      params: { repository: doc-coaster-updated, force: true }

  - name: doc-coaster-nn
    build_logs_to_retain: 2
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster
      - get: doc-coaster-nn
      - get: coaster-nn
        trigger: true
        passed: [test-coaster-nn]
      - get: container-misc
        trigger: true
    - task: gen-doc
      image: container-misc
      config:
        platform: linux
        inputs:
        - name: rust-blas
        - name: rust-cudnn
        - name: rust-cublas
        - name: coaster
        - name: coaster-nn
        - name: doc-coaster-nn
        outputs:
        - name: doc-coaster-nn-updated
        run:
          path: sh
          args:
          - -exc
          - |
            cd coaster-nn
            cargo doc --no-deps
            cd -
            git clone doc-coaster-nn doc-coaster-nn-updated
            rm -rf doc-coaster-nn-updated/*
            cp -rf coaster-nn/target/doc/* doc-coaster-nn-updated/
            cd doc-coaster-nn-updated
            echo "<meta http-equiv=refresh content=0;url=coaster_nn/index.html>" > index.html
            git config --global user.email "sirmergealot@spearow.io"
            git config --global user.name "Sir Mergealot"
            git add -A && git commit -m"doc/automatic: update" || true
    - put: doc-coaster-nn
      params: { repository: doc-coaster-nn-updated, force: true }

  - name: doc-coaster-blas
    build_logs_to_retain: 2
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster
      - get: doc-coaster-blas
      - get: coaster-blas
        trigger: true
        passed: [test-coaster-blas]
      - get: container-misc
        trigger: true
    - task: gen-doc
      image: container-misc
      config:
        platform: linux
        inputs:
        - name: rust-blas
        - name: rust-cudnn
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        - name: doc-coaster-blas
        outputs:
        - name: doc-coaster-blas-updated
        run:
          path: sh
          args:
          - -exc
          - |
            cd coaster-blas
            cargo doc --no-deps
            cd -
            git clone doc-coaster-blas doc-coaster-blas-updated
            rm -rf doc-coaster-blas-updated/*
            cp -rf coaster-blas/target/doc/* doc-coaster-blas-updated/
            cd doc-coaster-blas-updated
            echo "<meta http-equiv=refresh content=0;url=coaster_blas/index.html>" > index.html
            git config --global user.email "sirmergealot@spearow.io"
            git config --global user.name "Sir Mergealot"
            git add -A && git commit -m"doc/automatic: update" || true
    - put: doc-coaster-blas
      params: { repository: doc-coaster-blas-updated, force: true }

  - name: doc-greenglas
    build_logs_to_retain: 2
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster
      - get: doc-greenglas
      - get: greenglas
        trigger: true
        passed: [test-greenglas]
      - get: container-misc
        trigger: true
    - task: gen-doc
      image: container-misc
      config:
        platform: linux
        inputs:
        - name: coaster
        - name: rust-blas
        - name: rust-cublas
        - name: rust-cudnn
        - name: greenglas
        - name: doc-greenglas
        outputs:
        - name: doc-greenglas-updated
        run:
          path: sh
          args:
          - -exc
          - |
            cd greenglas
            cargo doc --no-deps
            cd -
            git clone doc-greenglas doc-greenglas-updated
            rm -rf doc-greenglas-updated/*
            cp -rf greenglas/target/doc/* doc-greenglas-updated/
            cd doc-greenglas-updated
            echo "<meta http-equiv=refresh content=0;url=greenglas/index.html>" > index.html
            git config --global user.email "sirmergealot@spearow.io"
            git config --global user.name "Sir Mergealot"
            git add -A && git commit -m"doc/automatic: update" || true
    - put: doc-greenglas
      params: { repository: doc-greenglas-updated, force: true }

  - name: doc-juice
    build_logs_to_retain: 2
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster-blas
      - get: coaster-nn
      - get: coaster
        passed: [test-coaster]
      - get: doc-juice
      - get: juice
        trigger: true
        #passed: [test-juice]
      - get: container-misc
        trigger: true
    - task: gen-doc
      image: container-misc
      config:
        platform: linux
        inputs:
        - name: coaster
        - name: coaster-nn
        - name: coaster-blas
        - name: rust-blas
        - name: rust-cublas
        - name: rust-cudnn
        - name: juice
        - name: doc-juice
        outputs:
        - name: doc-juice-updated
        run:
          path: sh
          args:
          - -exc
          - |
            cd juice
            cargo doc --no-deps
            cd doc
            mdbook build
            cd ../..

            git clone doc-juice doc-juice-updated
            rm -rf doc-juice-updated/*
            cp -rf juice/target/doc/* doc-juice-updated/
            cp -rf juice/doc/book doc-juice-updated/book
            cd doc-juice-updated
            echo "<meta http-equiv=refresh content=0;url=juice/index.html>" > index.html
            git config --global user.email "sirmergealot@spearow.io"
            git config --global user.name "Sir Mergealot"
            git add -A && git commit -m"doc/automatic: update" || true
    - put: doc-juice
      params: { repository: doc-juice-updated, force: true }


{% for which in ["", "pr-"] %}

  - name: {{ which }}test-rust-cudnn
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: {{ which }}rust-cudnn
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% if backend.name == "cuda" %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endif %}
{% endfor %}
{% endfor %}
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% if backend.name == "cuda" %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: {{ which }}rust-cudnn
        run:
          path: sh
          args:
          - -exc
          - |
{%- if backend.execute == BackendExecute::Test %}
            escalate
{%- endif %}
            prepare
            cd cudnn-sys
            cargo b
            cargo t
            cd -
            cd cudnn
            cargo b
            cargo t
          dir: {{ which }}rust-cudnn
{% endif %}
{% endfor %}
{% endfor %}

  - name: {{ which }}test-rust-cublas
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: {{ which }}rust-cublas
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% if backend.name == "cuda" %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endif %}
{% endfor %}
{% endfor %}
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% if backend.name == "cuda" %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: {{ which }}rust-cublas
        run:
          path: sh
          args:
          - -exc
          - |
{%- if backend.execute == BackendExecute::Test %}
            escalate
{%- endif %}
            prepare
            cd cublas-sys
            cargo b
            cargo t
            cd -
            cd cublas
            cargo b
            cargo t
          dir: {{ which }}rust-cublas
{% endif %}
{% endfor %}
{% endfor %}

  - name: {{ which }}test-rust-blas
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: {{ which }}rust-blas
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% if backend.name == "native" %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endif %}
{% endfor %}
{% endfor %}
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% if backend.name == "native" %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: {{ which }}rust-blas
        run:
          path: sh
          args:
          - -exc
          - |
            prepare
            cargo b
            cargo t

          dir: {{ which }}rust-blas
{% endif %}
{% endfor %}
{% endfor %}

  - name: {{ which }}test-coaster
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: {{ which }}coaster
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endfor %}
{% endfor %}
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: {{ which }}coaster
        caches:
        - path: target
        run:
          path: sh
          args:
          - -exc
          - |
{% include "cargo.yml" %}
          dir: {{ which }}coaster
{% endfor %}
{% endfor %}

  - name: {{ which }}test-coaster-blas
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cublas
        trigger: true
      - get: coaster
        trigger: true
        passed: [test-coaster]
      - get: {{ which }}coaster-blas
        trigger: true
      - get: rust-blas
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endfor %}
{% endfor %}
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        caches:
        - path: target
        run:
          path: sh
          args:
          - -exc
          - |
{% include "cargo.yml" %}
          dir: {{ which }}coaster-blas
{% endfor %}
{% endfor %}


  - name: {{ which }}test-coaster-nn
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cudnn
        trigger: true
      - get: rust-blas
        trigger: true
      - get: rust-cublas
        trigger: true
      - get: coaster
        passed: [test-coaster]
        trigger: true
      - get: coaster-blas
        trigger: true
      - get: {{ which }}coaster-nn
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endfor %}
{% endfor %}
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        - name: {{ which }}coaster-nn
        caches:
        - path: target
        run:
          path: sh
          args:
          - -exc
          - |
{% include "cargo.yml" %}
          dir: {{ which }}coaster-nn
{% endfor %}
{% endfor %}

  - name: {{ which }}test-greenglas
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster
        trigger: true
        passed: [test-coaster]
      - get: coaster-blas
        trigger: true
        passed: [test-coaster-blas]
      - get: coaster-nn
        trigger: true
        passed: [test-coaster-nn]
      - get: {{ which }}greenglas
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endfor %}
{% endfor %}
        passed: [test-coaster, test-coaster-nn, test-coaster-blas]
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: greenglas
        caches:
        - path: target
        run:
          path: sh
          args:
          - -exc
          - |
{% include "cargo.yml" %}
          dir: {{ which }}greenglas
{% endfor %}
{% endfor %}

  - name: {{ which }}test-juice
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster
        trigger: true
        passed: [test-coaster]
      - get: coaster-blas
        trigger: true
        passed: [test-coaster-blas]
      - get: coaster-nn
        trigger: true
        passed: [test-coaster-nn]
      - get: {{ which }}juice
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endfor %}
{% endfor %}
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        - name: coaster-nn
        - name: {{ which }}juice
        caches:
        - path: target
        run:
          path: sh
          args:
          - -exc
          - |
{% include "cargo.yml" %}
          dir: {{ which }}juice
{% endfor %}
{% endfor %}

  - name: {{ which }}test-juice-examples
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - aggregate:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: coaster-blas
      - get: coaster-nn
      - get: coaster
        trigger: true
        passed: [test-coaster]
      - get: greenglas
        trigger: true
        passed: [test-greenglas]
      - get: juice
        trigger: true
        passed: [test-juice]
      - get: {{ which }}juice-examples
        trigger: true
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
      - get: container-{{ testenv.name }}-{{ backend }}
        trigger: true
{% endfor %}
{% endfor %}
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
{% include "tags.yml" %}
    - task: {{ backend.execute }}-{{ testenv.name }}-{{ backend }}
      image: container-{{ testenv.name }}-{{ backend }}
      privileged: true
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: coaster
        - name: coaster-blas
        - name: coaster-nn
        - name: juice
        - name: {{ which }}juice-examples
        caches:
        - path: target
        run:
          path: sh
          args:
          - -exc
          - |
{% include "cargo.yml" %}
          dir: {{ which }}juice-examples
{% endfor %}
{% endfor %}
#################################
{% endfor %}
