resources:

{% for testenv in testenvs %}
{% for backend in testenv.backends %}
- name: container-{{ testenv.name }}-{{ backend }}
  type: registry-image
{% include "container-tags.yml" %}
  source:
    repository: quay.io/spearow/machine-learning-container-{{ testenv.name }}-{{ backend }}
{%- endfor -%}
{%- endfor %}

# - name: container-misc
#   type: registry-image
#   source:
#     repository: quay.io/spearow/doc-gen-container

{% include "master-resources.yml" %}

jobs:

{% include "master.yml" %}
