resources:
- name: git-continuous-integration
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/continuous-integration.git

{% include "container-resources.yml" %}

jobs:
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
  - name: build-{{ testenv.name }}-{{ backend }}
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
      params:
        build: container
        dockerfile: {{ testenv.name }}/{{ backend }}/
        tag_as_latest: true
{% endfor %}
{% endfor %}
