resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource


resources:

{% include "doc-resources.yml" %}

{% include "pr-resources.yml" %}

{% include "master-resources.yml" %}


{% for testenv in testenvs %}
{% for backend in testenv.backends %}
# TODO XXX currently there is a hack in place which puts
# TODO XXX a containerless concourse worker into the container
# TODO XXX as such this is not needed for default,cuda,opencl backends
# once fixed, use the "container-resources.yml" again
- name: container-{{ testenv }}-{{ backend }}
  type: registry-image
{% include "tags2.yml" %}
  source:
    repository: quay.io/spearow/machine-learning-container-{{ testenv }}-{{ backend }}
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
{%- endfor -%}
{%- endfor %}

- name: container-misc
  type: registry-image
  source:
    repository: quay.io/spearow/doc-gen-container
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))

groups:
- name: master
  jobs:
  - test-juice-*
  - example-*

- name: documentation
  jobs:
  - documentation-update

- name: pull-request
  jobs:
  - pr-test-juice*
  - pr-example-*

jobs:

{% include "doc.yml" %}

{% include "pr.yml" %}

{% include "master.yml" %}
