resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource


resources:

### DOC ###

{% include "doc-resources.yml" %}

### PULL REQUEST ###

{% include "pr-resources.yml" %}

### MASTER ###

{% include "master-resources.yml" %}


{% for testenv in testenvs %}
{% for backend in testenv.backends %}
- name: container-{{ testenv }}-{{ backend }}
  type: registry-image
{% include "tags2.yml" %}
  source:
    repository: quay.io/spearow/machine-learning-container-{{ testenv }}-{{ backend }}
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))
{%- endfor -%}
{%- endfor %}

- name: container-misc
  type: registry-image
  source:
    repository: quay.io/spearow/doc-gen-container
    username: ((quay-spearow-username))
    password: ((quay-spearow-password))

groups:
- name: master
  jobs:
  - test-juice-*
  - example-*

- name: documentation
  jobs:
  - documentation-update

- name: pull-request
  jobs:
  - pr-test-juice*
  - pr-example-*

jobs:

### DOC ###

{% include "doc.yml" %}

### PULL REQUEST ###

{% include "pr.yml" %}

### MASTER ###

{% include "master.yml" %}
