resources:
- name: git-ci
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/continuous-integration.git

{% include "container-resources.yml" %}
{% include "container-resources-preload.yml" %}

jobs:
  - name: build-misc
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true
    - get: container
      resource: container-misc

    - get: container-fedora-base
      params: { save: true }

    - task: gen-misc
      image: container
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/misc/Dockerfile ./copycat/
            cp -rfv ci/container/misc ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-misc
      inputs: detect
      params:
        load_base: container-fedora-base
        build: copycat
        tag_as_latest: true


{% for testenv in testenvs %}
  - name: create-oci-{{ testenv.name }}-base
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-fedora-base

    - task: composition
      image: container-fedora-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/{{ testenv.name }} ./copycat/
            cp -rfv ci/container/{{ testenv.name }}/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-{{ testenv.name }}-base
      inputs: detect
      params:
        build: copycat
        tag_as_latest: true

{% for backend in testenv.backends %}
  - name: create-oci-{{ testenv.name }}-{{ backend }}
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: container-{{ testenv.name }}-base
      passed: [create-oci-{{ testenv.name }}-base]
      params: { save: true }

    - task: composition
      image: container-{{ testenv.name }}-base
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/{{ testenv.name }} ./copycat/
            cp -rfv ci/container/{{ testenv.name }}/{{ backend }}/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/

    - put: container-{{ testenv.name }}-{{ backend }}
      inputs: detect
      params:
        load_base: container-{{ testenv.name }}-base
        build: copycat
        tag_as_latest: true

{% endfor %}
{%- endfor %}
