resources:
- name: git-continuous-integration
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/continuous-integration.git

{% include "container-resourses.yml" %}

jobs:
{% for testenv in testenvs %}
{% for backend in testenv.backends %}
  - name: build-{{ testenv.name }}-{{ backend }}
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - aggregate:
      - get: ci
        resource: git-continuous-integration
        trigger: true
      - get: container
    - task: gen-container
      image: container
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: recombined
        run:
          path: sh
          args:
          - -exc
          - |
            cp ci/container/{{ testenv.name }}/Dockerfile recombined/Dockerfile
            cp ci/container/{{ testenv.name }}/pkg.sh.{{ backend }} recombined/pkg.sh
            cp ci/container/escalate.sh recombined/escalate.sh

    - put: container-{{ testenv.name }}-{{ backend }}
      params:
        build: recombined
        tag_as_latest: true
{% endfor %}
{% endfor %}
